ECOCSystem/Controllers/GetDataController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Configuration;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Net.Http;
using ECOCSystem.Model;
using ECOCSystem.Tools;


namespace ECOCSystem.Controllers
{
    [AuthorizeUser]
    public class GetDataController : Controller
    {
        // GET: GetData
        public ActionResult Index()
        {
            return View();
        }
        [HttpGet]
        public ActionResult GetClientTitle(string search, int page, int pageSize)
        {
            using (var db = new ECOCEntities())
            {
                //int skip = page > 1 ? Convert.ToInt32(start) + 5 : 0;
                //int recordsTotal = 0;
                //bool more = true;


                var itemList = (from a in db.Title
                                from b in db.TitleType.Where(o => o.ID == a.TitleTypeID).DefaultIfEmpty()
                                where a.Active == true
                                select new
                                {
                                    id =  a.ID,
                                    text = a.Name
                                }).ToList();
              

                //Search itemList
                if (!string.IsNullOrWhiteSpace(search))
                {
                    itemList = itemList.Where(m => m.text != null && m.text.ToLower().Contains(search.ToLower())).ToList();
                }

                //Total size of itemList
                var itemsTotal = itemList.Count();

                //check next page itemList
                itemList = itemList.Skip((page * pageSize) - pageSize).Take(page * pageSize).ToList();

                var jsonResult = Json(new { items = itemList, page = page, pageSize = pageSize, total_count = itemsTotal }, JsonRequestBehavior.AllowGet);
                jsonResult.MaxJsonLength = int.MaxValue;
                return jsonResult;
            }
        }
        [HttpGet]
        public ActionResult GetClients(string search, int page, int pageSize)
        {
            using (var db = new ECOCEntities())
            {

                int Individual = 1;
                int Corporate = 2;
                int CorporateWithAssignee = 3;

                int curCompany = (int)CurrentUser.Details.CompanyID;
                int curBranch = (int)CurrentUser.Details.CompanyBranchID;

                var itemList = (from a in db.Client
                                from b in db.Title.Where(o => o.ID == a.TitleID).DefaultIfEmpty()
                                from c in db.TitleType.Where(o => o.ID == b.TitleTypeID).DefaultIfEmpty()
                                where a.Active == true &&
                                a.CompanyID == curCompany &&
                                a.BranchID == curBranch
                                select new
                                {
                                    id = a.ID,
                                    text = c.ID == Individual ? b.TitleAbbreviation+" "+ a.FirstName+" "+a.LastName+" "+a.MiddleName + " - " + c.Name
                                          : c.ID == Corporate ? a.CorpName + " - " + c.Name
                                          : c.ID == CorporateWithAssignee ? a.FirstName + " " + a.LastName + " " + a.MiddleName +" - " +a.CorpName +" - "+c.Name
                                          : "-"
                                }).ToList();

                //Search itemList
                if (!string.IsNullOrWhiteSpace(search))
                {
                    itemList = itemList.Where(m => m.text != null && m.text.ToLower().Contains(search.ToLower())).ToList();
                }

                //Total size of itemList
                var itemsTotal = itemList.Count();

                //check next page itemList
                itemList = itemList.Skip((page * pageSize) - pageSize).Take(page * pageSize).ToList();

                var jsonResult = Json(new { items = itemList, page = page, pageSize = pageSize, total_count = itemsTotal }, JsonRequestBehavior.AllowGet);
                jsonResult.MaxJsonLength = int.MaxValue;
                return jsonResult;
            }
        }
        [HttpGet]
        public ActionResult GetAddressTypes(string search, int page, int pageSize)
        {
            using (var db = new ECOCEntities())
            {


                var itemList = (from a in db.AddressType
                                select new
                                {
                                    id = a.ID,
                                    text = a.Name
                                }).ToList();



                //Search itemList
                if (!string.IsNullOrWhiteSpace(search))
                {
                    itemList = itemList.Where(m => m.text != null && m.text.ToLower().Contains(search.ToLower())).ToList();
                }

                //Total size of itemList
                var itemsTotal = itemList.Count();

                //check next page itemList
                itemList = itemList.Skip((page * pageSize) - pageSize).Take(page * pageSize).ToList();

                var jsonResult = Json(new { items = itemList, page = page, pageSize = pageSize, total_count = itemsTotal }, JsonRequestBehavior.AllowGet);
                jsonResult.MaxJsonLength = int.MaxValue;
                return jsonResult;
            }
        }
        [HttpGet]
        public ActionResult GetRegistrationTypes(string search, int page, int pageSize)
        {
            using (var db = new ECOCEntities())
            {
                //int skip = page > 1 ? Convert.ToInt32(start) + 5 : 0;
                //int recordsTotal = 0;
                //bool more = true;


                var itemList = (from a in db.RegistrationType
                                select new
                                {
                                    id = a.ID,
                                    text = a.Name
                                }).ToList();

                //Search itemList
                if (!string.IsNullOrWhiteSpace(search))
                {
                    itemList = itemList.Where(m => m.text != null && m.text.ToLower().Contains(search.ToLower())).ToList();
                }

                //Total size of itemList
                var itemsTotal = itemList.Count();

                //check next page itemList
                itemList = itemList.Skip((page * pageSize) - pageSize).Take(page * pageSize).ToList();

                var jsonResult = Json(new { items = itemList, page = page, pageSize = pageSize, total_count = itemsTotal }, JsonRequestBehavior.AllowGet);
                jsonResult.MaxJsonLength = int.MaxValue;
                return jsonResult;
            }
        }
        [HttpGet]
        public ActionResult GetCitylist(string search, int page, int pageSize)
        {
            using (var db = new ECOCEntities())
            {
                //int skip = page > 1 ? Convert.ToInt32(start) + 5 : 0;
                //int recordsTotal = 0;
                //bool more = true;


                var itemList = (from a in db.City
                                select new
                                {
                                    id = a.CityID,
                                    text = a.CityName
                                }).ToList();

                //Search itemList
                if (!string.IsNullOrWhiteSpace(search))
                {
                    itemList = itemList.Where(m => m.text != null && m.text.ToLower().Contains(search.ToLower())).ToList();
                }

                //Total size of itemList
                var itemsTotal = itemList.Count();

                //check next page itemList
                itemList = itemList.Skip((page * pageSize) - pageSize).Take(page * pageSize).ToList();

                var jsonResult = Json(new { items = itemList, page = page, pageSize = pageSize, total_count = itemsTotal }, JsonRequestBehavior.AllowGet);
                jsonResult.MaxJsonLength = int.MaxValue;
                return jsonResult;
            }
        }
        [HttpGet]
        public ActionResult GetProvinceList(string search, int page, int pageSize)
        {
            using (var db = new ECOCEntities())
            {
                //int skip = page > 1 ? Convert.ToInt32(start) + 5 : 0;
                //int recordsTotal = 0;
                //bool more = true;


                var itemList = (from a in db.Province
                                select new
                                {
                                    id = a.ProvinceID,
                                    text = a.ProvinceName
                                }).ToList();

                //Search itemList
                if (!string.IsNullOrWhiteSpace(search))
                {
                    itemList = itemList.Where(m => m.text != null && m.text.ToLower().Contains(search.ToLower())).ToList();
                }

                //Total size of itemList
                var itemsTotal = itemList.Count();

                //check next page itemList
                itemList = itemList.Skip((page * pageSize) - pageSize).Take(page * pageSize).ToList();

                var jsonResult = Json(new { items = itemList, page = page, pageSize = pageSize, total_count = itemsTotal }, JsonRequestBehavior.AllowGet);
                jsonResult.MaxJsonLength = int.MaxValue;
                return jsonResult;
            }
        }
        public ActionResult GetUserTypes(string search, int page, int pageSize)
        {
            using (var db = new ECOCEntities())
            {


                var itemList = (from a in db.UserType.Where(o => o.ID != (int)UserTypeEnum.SuperAdmin)
                                select new
                                {
                                    id = a.ID,

ECOCSystem/Views/Vehicle/BodyType.cshtml
@using ECOCSystem.Model
@model BodyTypeModel
@{
    ViewBag.Title = "BodyType";
    Layout = "~/Views/Shared/_Layout.cshtml";
    DataAnnotationsModelValidatorProvider.AddImplicitRequiredAttributeForValueTypes = false;
}

<section class="content">
    <div class="card card-success card-outline">
        <div class="card-header">
            <h3 class="card-title">Vehicle Body Type List</h3>
        </div>
        <div class="fab" id="addMake" type="button" data-toggle="modal" data-target="#modal-make-info" name="btnSubmit" title="" @*onclick="location.href='/Customer/Customer'"*@ data-original-title="Create New"> + </div>
        <div class="card-body">
            @using (Html.BeginForm("Vehicle", "Vehicle", null, FormMethod.Post, new { enctype = "multipart/form-data", id = "CompanyInfo_Form" }))
            {

                @Html.HiddenFor(m => m.BodyTypeID)
                <div id="" class="dataTables_wrapper dt-bootstrap4">
                    <div class="row">
                        <div class="col-sm-12">
                            <table id="table-BodyType" class="table table-head-fixed table-hover dataTable dtr-inline table-hover dt-responsive nowrap " style="min-width: 80em;cursor:pointer">
                                <thead>
                                    <tr>
                                        <th><center>Action Edit</center></th>
                                        <th>Body Type</th>
                                        <th>Body Type Abbreviation</th>
                                    </tr>
                                </thead>
                            </table>
                        </div>
                    </div>
                </div>

                <div class="modal fade" id="modal-make-info" style="display: none;" aria-hidden="true">
                    <div class="modal-dialog modal-xl">

                    </div>

                </div>

                <div class="modal fade" id="modal-make-series" style="display: none;" aria-hidden="true">
                    <div class="modal-dialog modal-lg">

                    </div>

                </div>

                <div class="modal fade" id="modal-make-body" style="display: none;" aria-hidden="true">
                    <div class="modal-dialog modal-lg">

                    </div>

                </div>
                <div class="modal fade" id="modal-make-color" style="display: none;" aria-hidden="true">
                    <div class="modal-dialog modal-lg">

                    </div>

                </div>
            }

        </div>
    </div>





</section>
<script>
    $(document).ready(function () {

        getBodyTypeList();


    });



   function getBodyTypeList() {

        let cntRow = 0;
       BodyType_table = $("#table-BodyType").DataTable({
            "processing": true, // for show progress bar
            "serverSide": false, // for process server side
            "filter": true, // this is for disable filter (search box)
            "orderMulti": false, // for disable multiple column at once
            "scrollX": true,
            "scrollY": true,
            "destroy": true,


            "order": [],
            "dom":
                "<'row'<'col-sm-12 col-md-6'l><'col-sm-12 col-md-6'f>>" +
                "<'row'<'col-sm-12'tr>>" +
                "<'row'<'col-sm-12 col-md-5'p><'col-sm-12 col-md-7'i>>",
            "ajax": {
                "url": '@Url.Action("GetAllBodyTypeList", "Vehicle")',
                "type": "POST",
                "datatype": "json",
/*                "data": { "CompanyID": CompanyID, "BranchID": BranchID },*/
                "beforeSend": function () {
                    $('#loadingScreen').show();
                    cntRow = 0;
                },
                "complete": function (row, data, dataIndex) {


                    $('#loadingScreen').hide();
                }
            },
            "createdRow": function (row, data, dataIndex) {

            },
            "columns": [
                {
                    "className": "VehicleBodyTypeID", "data": null, "name": "VehicleBodyTypeID",
                    render: function (data, type, row) {
                        return `<center>
                                  <div class="">
                                         <span type="button" data-toggle="modal" data-target="#modal-make-info"" onclick="EditMake(`+ data.VehicleBodyTypeID + `,'` + data.VehicleBodyTypeID+`')">
                                            <i class="fa fa-pencil-alt fa-lg text-primary" style="padding: 0px"></i>
                                        </span>
                                    </div>
                                 </div>
                              </center>`
                    }, "autoWidth": true
                },
                { "className": "VehicleBodyTypeName", "data": "VehicleBodyTypeName", "name": "VehicleBodyTypeName", "autoWidth": true },
                { "className": "VehicleBodyAbbr", "data": "VehicleBodyAbbr", "name": "VehicleBodyAbbr", "autoWidth": true },



            ]
        });
       $('#table-BodyType_paginate').parent('div').parent('div').css('flex-direction', 'row-reverse').css('margin', '12px');



    };
</script>

ECOCSystem/Views/Vehicle/Classification.cshtml
@using ECOCSystem.Model
@model ClassificationModel
@{
    ViewBag.Title = "Vehicle Classification";
    Layout = "~/Views/Shared/_Layout.cshtml";
    DataAnnotationsModelValidatorProvider.AddImplicitRequiredAttributeForValueTypes = false;
}

<section class="content">
    <div class="card card-success card-outline">
        <div class="card-header">
            <h3 class="card-title">Vehicle Classification List</h3>
        </div>
        <div class="fab" id="addMake" type="button" data-toggle="modal" data-target="#modal-make-info" name="btnSubmit" title="" @*onclick="location.href='/Customer/Customer'"*@ data-original-title="Create New"> + </div>
        <div class="card-body">
            @using (Html.BeginForm("Vehicle", "Vehicle", null, FormMethod.Post, new { enctype = "multipart/form-data", id = "CompanyInfo_Form" }))
            {

                @Html.HiddenFor(m => m.ClassificationID)
                <div id="" class="dataTables_wrapper dt-bootstrap4">
                    <div class="row">
                        <div class="col-sm-12">
                            <table id="table-Classification" class="table table-head-fixed table-hover dataTable dtr-inline table-hover dt-responsive nowrap " style="min-width: 80em;cursor:pointer">
                                <thead>
                                    <tr>
                                        <th><center>Action Edit</center></th>
                                        <th>Vehicle Classification</th>
                                    </tr>
                                </thead>
                            </table>
                        </div>
                    </div>
                </div>

                <div class="modal fade" id="modal-make-info" style="display: none;" aria-hidden="true">
                    <div class="modal-dialog modal-xl">

                    </div>

                </div>
            }

        </div>
    </div>





</section>
<script>
    $(document).ready(function () {

        getClassficationList();


    });



   function getClassficationList() {

        let cntRow = 0;
       Classification_table = $("#table-Classification").DataTable({
            "processing": true, // for show progress bar
            "serverSide": false, // for process server side
            "filter": true, // this is for disable filter (search box)
            "orderMulti": false, // for disable multiple column at once
            "scrollX": true,
            "scrollY": true,
            "destroy": true,


            "order": [],
            "dom":
                "<'row'<'col-sm-12 col-md-6'l><'col-sm-12 col-md-6'f>>" +
                "<'row'<'col-sm-12'tr>>" +
                "<'row'<'col-sm-12 col-md-5'p><'col-sm-12 col-md-7'i>>",
            "ajax": {
                "url": '@Url.Action("GetClassificationList", "Vehicle")',
                "type": "POST",
                "datatype": "json",
/*                "data": { "CompanyID": CompanyID, "BranchID": BranchID },*/
                "beforeSend": function () {
                    $('#loadingScreen').show();
                    cntRow = 0;
                },
                "complete": function (row, data, dataIndex) {


                    $('#loadingScreen').hide();
                }
            },
            "createdRow": function (row, data, dataIndex) {

            },
            "columns": [
                {
                    "className": "VehicleClassificationID", "data": null, "name": "VehicleClassificationID",
                    render: function (data, type, row) {
                        return `<center>
                                  <div class="">
                                         <span type="button" data-toggle="modal" data-target="#modal-make-info"" onclick="EditMake(`+ data.VehicleClassificationID + `,'` + data.VehicleClassificationID+`')">
                                            <i class="fa fa-pencil-alt fa-lg text-primary" style="padding: 0px"></i>
                                        </span>
                                    </div>
                                 </div>
                              </center>`
                    }, "autoWidth": true
                },
                { "className": "VehicleClassificationName", "data": "VehicleClassificationName", "name": "VehicleClassificationName", "autoWidth": true },

            ]
        });
       $('#table-Classification_paginate').parent('div').parent('div').css('flex-direction', 'row-reverse').css('margin', '12px');



    };
</script>

ECOCSystem/Views/Vehicle/_AddSeries.cshtml
@using ECOCSystem.Model
@model List<Series>

<!-- Main content -->



<div class="modal-content ">
    <div id="" class="overlay d-none">
        @*<i class="fas fa-2x fa-sync fa-spin"></i>*@
    </div>
    <div class="modal-header">
        <h4 class="modal-title">Add Series</h4>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true"><i class="fa" fa></i>×</span>
        </button>
    </div>
    <div class="modal-body " style="padding:2rem;">

        <section class="content ">

            <table id="tbl_Series_list" class="table table-head-fixed table-hover dataTable dtr-inline table-hover dt-responsive" style="min-width: 45em">
                <thead>
                    <tr>
                        <th><center>Select</center></th>
                        <th>Model Name</th>
                        <th>Variant</th>
                        <th>Body Type</th>
                    </tr>
                </thead>
                @*<tbody id="color_tbdy">
                @for (int i = 0; i < Model.Count(); i++)
                {
                    <tr>
                        <td style="width:20%">
                            <center>
                                <div class="icheck-success d-inline">
                                    @Html.CheckBoxFor(o => Model[i].isChecked, new { id = i, @class = "checkbox_all", Name = "SeriesList[" + i + "].isChecked" })
                                    <label for="@i"></label>
                                </div>
                            </center>
                        </td>
                        <td style="width:80%">
                            @Html.HiddenFor(o => Model[i].SeriesID, new { Name = "SeriesList[" + i + "].ColorID" })
                            @Html.DisplayFor(o => Model[i].Model, new { Name = "SeriesList[" + i + "].Model" })
                            @Html.DisplayFor(o => Model[i].Variant, new { Name = "SeriesList[" + i + "].Variant" })
                            @Html.DisplayFor(o => Model[i].BodyType, new { Name = "SeriesList[" + i + "].BodyType" })
                        </td>
                    </tr>
                }
            </tbody>*@
            </table>



        </section>
    </div>
    <div id="addSeriesOption" class="modal-footer justify-content-between submit-btn">
        <button type="button" onclick="closeModalBranch()" class="btn btn-default">Cancel</button>
        <button type="button" id="submit_addMake" value="ADDMAKE" class="btn btn-success">ADD</button>
    </div>
</div>
<script>


</script>

ECOCSystem/Views/Vehicle/_Model.cshtml
@using ECOCSystem.Model
@model MVModel


<div class="modal-content ">
    <div id="model-overlay" class="overlay d-none">
        @*<i class="fas fa-2x fa-sync fa-spin"></i>*@
    </div>
    <div class="modal-header">
        <h4 id="model-title" class="modal-title">Vehicle Model Information</h4>
        <button type="button" class="close" onclick="closeModalModel()" aria-label="Close">
            <span aria-hidden="true"><i class="fa" fa></i>×</span>
        </button>
    </div>
    <div class="modal-body " style="padding:2rem;">

        <section class="content ">

            <div id="example2_wrapper" class="dataTables_wrapper dt-bootstrap4">
                <div class="row">
                    <div class="col-sm-12">
                        @Html.HiddenFor(m => m.ModelID)

                        @Html.AntiForgeryToken()
                        <section class="row mt-4 pb-4 ">
                            @*<i class="fas fa-2x fa-sync fa-spin"></i>*@
                            <div class="form-group col-lg-6">
                                @Html.LabelFor(o => o.Model)
                                <div class="input-group">@Html.TextBoxFor(o => o.Model, new { @class = "form-control input-style", placeholder = "Vehicle Model" })</div>
                                @Html.ValidationMessageFor(o => o.Model)
                            </div>
                            <div class="form-group col-lg-6">
                                @Html.LabelFor(m => m.SelectedBodyTypeID)
                                <div class="input-group">
                                    @Html.DropDownListFor(m => m.SelectedBodyTypeID, new SelectList(Model.VehicleBodyList, "ID", "Info"), "Select Body Type", new { @class = "form-control select2 select2Ajax", select2Ajax_url = Url.Action("GetVehicleBodyList2", "GetData") })
                                </div>
                                @Html.ValidationMessageFor(m => m.SelectedBodyTypeID, "", new { @class = "" })
                            </div>
                        </section>

                        <section id="ModelOptions" class="infoButtons row mt-4 pb-4 submit-btn">
                        </section>

                        <section class="row pb-4">
                            <div class="col-12 col-sm-12 card">
                                <div class="cptl-title-header card-header " style="display: flex; align-items: center;">
                                    <label>Model Variant List</label>
                                    <div class="uiverse ">
                                        <span class="tooltip">Add new Variant</span>
                                        <span type="button" id="addVariant" class="" data-toggle="modal" data-target="#modal-model-variant">
                                            +
                                        </span>
                                    </div>
                                </div>
                                <div class="card-body">
                                    <div id="example2_wrapper" class="dataTables_wrapper dt-bootstrap4">
                                        <div class="row">
                                            <div class="col-sm-12">
                                                <table id="tbl_Variant" class="table table-head-fixed table-hover dataTable dtr-inline table-hover dt-responsive" style=" min-width: 58em">
                                                    <thead>
                                                        <tr>
                                                            <th style="width:150px"><center>Action Edit</center></th>
                                                            <th style="width:150px"><center>Action Remove</center></th>
                                                            <th>Variant</th>
                                                        </tr>
                                                    </thead>
                                                </table>

                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </section>
                    </div>
                </div>
            </div>


            <div class="modal fade" id="modal-model-variant" style="display: none;" aria-hidden="true">
                <div class="modal-dialog modal-lg">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h4 class="modal-title">Variant Information</h4>
                            <button type="button" class="close" onclick="closeModalVariant()" aria-label="Close">
                                <span aria-hidden="true"><i class="fa" fa></i>×</span>
                            </button>
                        </div>
                        <div class="modal-body @*overlay*@" style="padding:2rem;">
                            @Html.HiddenFor(m => m.VariantID)
                            <section class="row pb-4">
                                @*<i class="fas fa-2x fa-sync fa-spin"></i>*@
                                <div class="form-group col-lg-12">
                                    @Html.LabelFor(o => o.VehicleVariant)
                                    <div class="input-group">@Html.TextBoxFor(o => o.VehicleVariant, new { @class = "form-control input-style", placeholder = "Variant Name" })</div>
                                    @Html.ValidationMessageFor(o => o.VehicleVariant)
                                </div>
                            </section>
                        </div>
                        <div id="variantOptions" class="modal-footer justify-content-between submit-btn">

                        </div>
                    </div>
                </div>

            </div>

        </section>
    </div>
    @*<div id="addressOption" class="modal-footer justify-content-between submit-btn">
        </div>*@
</div>
<script>

    $(document).ready(function () {



        $('#addVariant').on('click', function () {


            $('#ModelInfo_Model').rules('remove');
            $('#ModelInfo_SelectedBodyTypeID').rules('remove');



            $('#variantOptions').empty();
            $('#variantOptions').append(`<button type="button" id="submit_addMake" value="ADDMAKE" class="btn btn-default">Cancel</button>
                                       <button type="button" id="submit_addVariant" value="ADDMAKE" class="btn btn-success">Save</button> `)

            $('#submit_addVariant').on('click', function () {
                submitForm("ADDVARIANT");
            });
        });

    });


 

</script>

ECOCSystem/Views/Vehicle/_SeriesInfo.cshtml
@using ECOCSystem.Model
@using ECOCSystem.Tools
@model MVModel


@Html.HiddenFor(m => m.SeriesID)
<div class="modal-content">
    <div class="modal-header">
        <h4 class="modal-title">Vehicle Series Information</h4>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true"><i class="fa" fa></i>×</span>
        </button>
    </div>
    <div class="modal-body @*overlay*@" style="padding:2rem;">

        <section class="row mt-4 pb-4 ">
            @*<i class="fas fa-2x fa-sync fa-spin"></i>*@

            <div class="form-group col-lg-4">
                @Html.LabelFor(o => o.Model)
                <div class="input-group">@Html.TextBoxFor(o => o.Model, new { @class = "form-control input-style", placeholder = "Vehicle Model" })</div>
                @Html.ValidationMessageFor(o => o.Model)
            </div>
            <div class="form-group col-lg-4">
                @Html.LabelFor(o => o.VehicleVariant)
                <div class="input-group">@Html.TextBoxFor(o => o.VehicleVariant, new { @class = "form-control input-style", placeholder = "Vehicle Variant" })</div>
                @Html.ValidationMessageFor(o => o.VehicleVariant)
            </div>
            <div class="form-group col-lg-4">
                @Html.LabelFor(m => m.SelectedBodyTypeID)
                <div class="input-group">
                    @Html.DropDownListFor(m => m.SelectedBodyTypeID, new SelectList(Model.VehicleBodyList, "ID", "Info"), "Select Body Type", new { @class = "form-control select2 select2Ajax", select2Ajax_url = Url.Action("GetVehicleBodyList", "GetData") })
                </div>
                @Html.ValidationMessageFor(m => m.SelectedBodyTypeID, "", new { @class = "" })
            </div>
        </section>
    </div>
    <div id="SeriesOption" class="modal-footer justify-content-between submit-btn">
    </div>
</div>
<script>


    $(document).ready(function () {

        //$('#addAddress').on('click', function () {
        //    $('#addressOption').empty();
        //    $('#addressOption').append(`<button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
        //    <button type="button" id="submit_Address" class="btn btn-success">Save </button>  `)

        //    $('#submit_Address').on('click', function () {
        //        submitForm("ADDADDRESS");
        //    });
        //});


    });


</script>